name: CI
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
    - develop
    - feature/*
jobs:
  test:
    name: Test
    runs-on: macOS-latest
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,OS=12.2,name=iPhone X', 'platform=tvOS Simulator,OS=12.2,name=Apple TV 4K']
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build and test
        run: |
          cd Texstyle
          xcodebuild clean test -project Texstyle.xcodeproj -scheme Texstyle -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
          bash <(curl -s https://codecov.io/bash)
        env: 
         destination: ${{ matrix.destination }}


# jobs:
#   test:
#     # Job name is Test
#     name: Test
#     # This job runs on macOS
#     runs-on: macOS-latest
#     strategy:
#       matrix:
#         destination: ['platform=iOS Simulator,OS=12.4,name=iPhone 8']
#         xcode: ['/Applications/Xcode_10.3.app/Contents/Developer']
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v1
#       - name: Bundle Install
#         run: bundle install
#       - name: Dependencies
#         run: 
#           bundle exec pod install
#         env:
#           DEVELOPER_DIR: ${{ matrix.xcode }}
#       - name: Build and test
#         run: bundle exec fastlane scan --destination "${destination}" --scheme "YOUR_APP_SCHEME"
#         env:
#           destination: ${{ matrix.destination }}
#           DEVELOPER_DIR: ${{ matrix.xcode }}
#       - name: Archive Failed Tests artifacts
#         if: failure()
#         uses: actions/upload-artifact@v1
#         with:
#           name: FailureDiff
#           path: YouAppTests/FailureDiffs
#       - name: Releasing
#         run: bundle exec fastlane release
#         env:
#           DEVELOPER_DIR: ${{ matrix.xcode }}
#           YOUR_ENVIRONMENT_VARIABLES_HERE: ${{ secret.XXX }}
