name: CI
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
    - develop
#     - feature/*
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@master
    - name: Install Dependences
      run: |
        cd Nousdigital
        pod repo update
        pod install
      shell: bash
    - name: Start xcodebuild test
      run: xcodebuild clean -workspace "Nousdigital.xcworkspace" -scheme "Nousdigital" -destination "platform=iOS Simulator,name=iPhone 8,OS=latest"
    - name: Archive xcodebuild 
      run: xcodebuild -workspace Nousdigital.xcworkspace -scheme Nousdigital -sdk iphoneos -configuration AppStoreDistribution archive -archivePath $PWD/build/Nousdigital.xcarchive

    
